/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMachineDslScopeProvider extends DelegatingScopeProvider {
}
