/**
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.machineDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jump</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link statemachine.dsl.machineDsl.Jump#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see statemachine.dsl.machineDsl.MachineDslPackage#getJump()
 * @model
 * @generated
 */
public interface Jump extends Command
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(State)
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getJump_Target()
   * @model
   * @generated
   */
  State getTarget();

  /**
   * Sets the value of the '{@link statemachine.dsl.machineDsl.Jump#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(State value);

} // Jump
