/**
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.machineDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see statemachine.dsl.machineDsl.MachineDslFactory
 * @model kind="package"
 * @generated
 */
public interface MachineDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "machineDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/machineDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "machineDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MachineDslPackage eINSTANCE = statemachine.dsl.machineDsl.impl.MachineDslPackageImpl.init();

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.MachineImpl <em>Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.MachineImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getMachine()
   * @generated
   */
  int MACHINE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__FIELDS = 1;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__STATES = 2;

  /**
   * The number of structural features of the '<em>Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.FieldImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getField()
   * @generated
   */
  int FIELD = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = 0;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.StateImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getState()
   * @generated
   */
  int STATE = 2;

  /**
   * The feature id for the '<em><b>Initial</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__INITIAL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 1;

  /**
   * The feature id for the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__ENTRY = 2;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__EVENTS = 3;

  /**
   * The feature id for the '<em><b>Exit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__EXIT = 4;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.EntryImpl <em>Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.EntryImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getEntry()
   * @generated
   */
  int ENTRY = 3;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.ExitImpl <em>Exit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.ExitImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getExit()
   * @generated
   */
  int EXIT = 4;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Exit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXIT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.EventImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.CommandImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 6;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.JumpImpl <em>Jump</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.JumpImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getJump()
   * @generated
   */
  int JUMP = 7;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JUMP__TARGET = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Jump</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JUMP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.PrintImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 8;

  /**
   * The feature id for the '<em><b>Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__ARGUMENTS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.PrintArgumentImpl <em>Print Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.PrintArgumentImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getPrintArgument()
   * @generated
   */
  int PRINT_ARGUMENT = 9;

  /**
   * The number of structural features of the '<em>Print Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_ARGUMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.StringArgumentImpl <em>String Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.StringArgumentImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getStringArgument()
   * @generated
   */
  int STRING_ARGUMENT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ARGUMENT__VALUE = PRINT_ARGUMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_ARGUMENT_FEATURE_COUNT = PRINT_ARGUMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.FieldReferenceImpl <em>Field Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.FieldReferenceImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getFieldReference()
   * @generated
   */
  int FIELD_REFERENCE = 11;

  /**
   * The feature id for the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_REFERENCE__FIELD = PRINT_ARGUMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Field Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_REFERENCE_FEATURE_COUNT = PRINT_ARGUMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link statemachine.dsl.machineDsl.impl.IncrementFieldImpl <em>Increment Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see statemachine.dsl.machineDsl.impl.IncrementFieldImpl
   * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getIncrementField()
   * @generated
   */
  int INCREMENT_FIELD = 12;

  /**
   * The feature id for the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT_FIELD__FIELD = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Increment Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT_FIELD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Machine <em>Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Machine</em>'.
   * @see statemachine.dsl.machineDsl.Machine
   * @generated
   */
  EClass getMachine();

  /**
   * Returns the meta object for the attribute '{@link statemachine.dsl.machineDsl.Machine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see statemachine.dsl.machineDsl.Machine#getName()
   * @see #getMachine()
   * @generated
   */
  EAttribute getMachine_Name();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.Machine#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see statemachine.dsl.machineDsl.Machine#getFields()
   * @see #getMachine()
   * @generated
   */
  EReference getMachine_Fields();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.Machine#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see statemachine.dsl.machineDsl.Machine#getStates()
   * @see #getMachine()
   * @generated
   */
  EReference getMachine_States();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see statemachine.dsl.machineDsl.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link statemachine.dsl.machineDsl.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see statemachine.dsl.machineDsl.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see statemachine.dsl.machineDsl.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link statemachine.dsl.machineDsl.State#isInitial <em>Initial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Initial</em>'.
   * @see statemachine.dsl.machineDsl.State#isInitial()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Initial();

  /**
   * Returns the meta object for the attribute '{@link statemachine.dsl.machineDsl.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see statemachine.dsl.machineDsl.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference '{@link statemachine.dsl.machineDsl.State#getEntry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Entry</em>'.
   * @see statemachine.dsl.machineDsl.State#getEntry()
   * @see #getState()
   * @generated
   */
  EReference getState_Entry();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.State#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see statemachine.dsl.machineDsl.State#getEvents()
   * @see #getState()
   * @generated
   */
  EReference getState_Events();

  /**
   * Returns the meta object for the containment reference '{@link statemachine.dsl.machineDsl.State#getExit <em>Exit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exit</em>'.
   * @see statemachine.dsl.machineDsl.State#getExit()
   * @see #getState()
   * @generated
   */
  EReference getState_Exit();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Entry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry</em>'.
   * @see statemachine.dsl.machineDsl.Entry
   * @generated
   */
  EClass getEntry();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.Entry#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see statemachine.dsl.machineDsl.Entry#getCommands()
   * @see #getEntry()
   * @generated
   */
  EReference getEntry_Commands();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Exit <em>Exit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exit</em>'.
   * @see statemachine.dsl.machineDsl.Exit
   * @generated
   */
  EClass getExit();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.Exit#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see statemachine.dsl.machineDsl.Exit#getCommands()
   * @see #getExit()
   * @generated
   */
  EReference getExit_Commands();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see statemachine.dsl.machineDsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link statemachine.dsl.machineDsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see statemachine.dsl.machineDsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.Event#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see statemachine.dsl.machineDsl.Event#getCommands()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Commands();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see statemachine.dsl.machineDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Jump <em>Jump</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Jump</em>'.
   * @see statemachine.dsl.machineDsl.Jump
   * @generated
   */
  EClass getJump();

  /**
   * Returns the meta object for the reference '{@link statemachine.dsl.machineDsl.Jump#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see statemachine.dsl.machineDsl.Jump#getTarget()
   * @see #getJump()
   * @generated
   */
  EReference getJump_Target();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see statemachine.dsl.machineDsl.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference list '{@link statemachine.dsl.machineDsl.Print#getArguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arguments</em>'.
   * @see statemachine.dsl.machineDsl.Print#getArguments()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Arguments();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.PrintArgument <em>Print Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Argument</em>'.
   * @see statemachine.dsl.machineDsl.PrintArgument
   * @generated
   */
  EClass getPrintArgument();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.StringArgument <em>String Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Argument</em>'.
   * @see statemachine.dsl.machineDsl.StringArgument
   * @generated
   */
  EClass getStringArgument();

  /**
   * Returns the meta object for the attribute '{@link statemachine.dsl.machineDsl.StringArgument#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see statemachine.dsl.machineDsl.StringArgument#getValue()
   * @see #getStringArgument()
   * @generated
   */
  EAttribute getStringArgument_Value();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.FieldReference <em>Field Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field Reference</em>'.
   * @see statemachine.dsl.machineDsl.FieldReference
   * @generated
   */
  EClass getFieldReference();

  /**
   * Returns the meta object for the reference '{@link statemachine.dsl.machineDsl.FieldReference#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Field</em>'.
   * @see statemachine.dsl.machineDsl.FieldReference#getField()
   * @see #getFieldReference()
   * @generated
   */
  EReference getFieldReference_Field();

  /**
   * Returns the meta object for class '{@link statemachine.dsl.machineDsl.IncrementField <em>Increment Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Increment Field</em>'.
   * @see statemachine.dsl.machineDsl.IncrementField
   * @generated
   */
  EClass getIncrementField();

  /**
   * Returns the meta object for the reference '{@link statemachine.dsl.machineDsl.IncrementField#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Field</em>'.
   * @see statemachine.dsl.machineDsl.IncrementField#getField()
   * @see #getIncrementField()
   * @generated
   */
  EReference getIncrementField_Field();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MachineDslFactory getMachineDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.MachineImpl <em>Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.MachineImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getMachine()
     * @generated
     */
    EClass MACHINE = eINSTANCE.getMachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MACHINE__NAME = eINSTANCE.getMachine_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE__FIELDS = eINSTANCE.getMachine_Fields();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE__STATES = eINSTANCE.getMachine_States();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.FieldImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.StateImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Initial</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__INITIAL = eINSTANCE.getState_Initial();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Entry</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__ENTRY = eINSTANCE.getState_Entry();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__EVENTS = eINSTANCE.getState_Events();

    /**
     * The meta object literal for the '<em><b>Exit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__EXIT = eINSTANCE.getState_Exit();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.EntryImpl <em>Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.EntryImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getEntry()
     * @generated
     */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTRY__COMMANDS = eINSTANCE.getEntry_Commands();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.ExitImpl <em>Exit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.ExitImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getExit()
     * @generated
     */
    EClass EXIT = eINSTANCE.getExit();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXIT__COMMANDS = eINSTANCE.getExit_Commands();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.EventImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__COMMANDS = eINSTANCE.getEvent_Commands();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.CommandImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.JumpImpl <em>Jump</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.JumpImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getJump()
     * @generated
     */
    EClass JUMP = eINSTANCE.getJump();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JUMP__TARGET = eINSTANCE.getJump_Target();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.PrintImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Arguments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__ARGUMENTS = eINSTANCE.getPrint_Arguments();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.PrintArgumentImpl <em>Print Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.PrintArgumentImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getPrintArgument()
     * @generated
     */
    EClass PRINT_ARGUMENT = eINSTANCE.getPrintArgument();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.StringArgumentImpl <em>String Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.StringArgumentImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getStringArgument()
     * @generated
     */
    EClass STRING_ARGUMENT = eINSTANCE.getStringArgument();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_ARGUMENT__VALUE = eINSTANCE.getStringArgument_Value();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.FieldReferenceImpl <em>Field Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.FieldReferenceImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getFieldReference()
     * @generated
     */
    EClass FIELD_REFERENCE = eINSTANCE.getFieldReference();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_REFERENCE__FIELD = eINSTANCE.getFieldReference_Field();

    /**
     * The meta object literal for the '{@link statemachine.dsl.machineDsl.impl.IncrementFieldImpl <em>Increment Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see statemachine.dsl.machineDsl.impl.IncrementFieldImpl
     * @see statemachine.dsl.machineDsl.impl.MachineDslPackageImpl#getIncrementField()
     * @generated
     */
    EClass INCREMENT_FIELD = eINSTANCE.getIncrementField();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INCREMENT_FIELD__FIELD = eINSTANCE.getIncrementField_Field();

  }

} //MachineDslPackage
