/**
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.machineDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see statemachine.dsl.machineDsl.MachineDslPackage#getPrintArgument()
 * @model
 * @generated
 */
public interface PrintArgument extends EObject
{
} // PrintArgument
