/**
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.machineDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link statemachine.dsl.machineDsl.State#isInitial <em>Initial</em>}</li>
 *   <li>{@link statemachine.dsl.machineDsl.State#getName <em>Name</em>}</li>
 *   <li>{@link statemachine.dsl.machineDsl.State#getEntry <em>Entry</em>}</li>
 *   <li>{@link statemachine.dsl.machineDsl.State#getEvents <em>Events</em>}</li>
 *   <li>{@link statemachine.dsl.machineDsl.State#getExit <em>Exit</em>}</li>
 * </ul>
 *
 * @see statemachine.dsl.machineDsl.MachineDslPackage#getState()
 * @model
 * @generated
 */
public interface State extends EObject
{
  /**
   * Returns the value of the '<em><b>Initial</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial</em>' attribute.
   * @see #setInitial(boolean)
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getState_Initial()
   * @model
   * @generated
   */
  boolean isInitial();

  /**
   * Sets the value of the '{@link statemachine.dsl.machineDsl.State#isInitial <em>Initial</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial</em>' attribute.
   * @see #isInitial()
   * @generated
   */
  void setInitial(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link statemachine.dsl.machineDsl.State#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Entry</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entry</em>' containment reference.
   * @see #setEntry(Entry)
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getState_Entry()
   * @model containment="true"
   * @generated
   */
  Entry getEntry();

  /**
   * Sets the value of the '{@link statemachine.dsl.machineDsl.State#getEntry <em>Entry</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entry</em>' containment reference.
   * @see #getEntry()
   * @generated
   */
  void setEntry(Entry value);

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link statemachine.dsl.machineDsl.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getState_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>Exit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit</em>' containment reference.
   * @see #setExit(Exit)
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getState_Exit()
   * @model containment="true"
   * @generated
   */
  Exit getExit();

  /**
   * Sets the value of the '{@link statemachine.dsl.machineDsl.State#getExit <em>Exit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit</em>' containment reference.
   * @see #getExit()
   * @generated
   */
  void setExit(Exit value);

} // State
