/**
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.machineDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link statemachine.dsl.machineDsl.StringArgument#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see statemachine.dsl.machineDsl.MachineDslPackage#getStringArgument()
 * @model
 * @generated
 */
public interface StringArgument extends PrintArgument
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see statemachine.dsl.machineDsl.MachineDslPackage#getStringArgument_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link statemachine.dsl.machineDsl.StringArgument#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // StringArgument
