/**
 *
 * $Id$
 */
package statemachine.model.validation;

import org.eclipse.emf.common.util.EList;

import statemachine.model.Entry;
import statemachine.model.Event;
import statemachine.model.Exit;

/**
 * A sample validator interface for {@link statemachine.model.State}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateInitial(boolean value);
	boolean validateEntry(Entry value);
	boolean validateExit(Exit value);
	boolean validateEvents(EList<Event> value);
}
