/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MachineDslStandaloneSetup extends MachineDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MachineDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
