/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MachineDslRuntimeModule extends AbstractMachineDslRuntimeModule {
}
