/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import statemachine.dsl.ui.internal.DslActivator;

public class MachineDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("statemachine.dsl.MachineDsl");
	}

}
