/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMachineDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(statemachine.dsl.machineDsl.MachineDslPackage.eINSTANCE);
		return result;
	}
}
