/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class MachineDslIdeModule extends AbstractMachineDslIdeModule {
}
