/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import statemachine.dsl.parser.antlr.internal.InternalMachineDslParser;
import statemachine.dsl.services.MachineDslGrammarAccess;

public class MachineDslParser extends AbstractAntlrParser {

	@Inject
	private MachineDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMachineDslParser createParser(XtextTokenStream stream) {
		return new InternalMachineDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Machine";
	}

	public MachineDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MachineDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
