/**
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.machineDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import statemachine.dsl.machineDsl.MachineDslPackage;
import statemachine.dsl.machineDsl.PrintArgument;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print Argument</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintArgumentImpl extends MinimalEObjectImpl.Container implements PrintArgument
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintArgumentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MachineDslPackage.Literals.PRINT_ARGUMENT;
  }

} //PrintArgumentImpl
