/*
 * generated by Xtext 2.31.0
 */
package statemachine.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MachineDslUiModule extends AbstractMachineDslUiModule {

	public MachineDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
